
version: '3'
services:
  
  app:
    build: app/.
    depends_on:
      - db

    environment:
     - SQLALCHEMY_DATABASE_URI=mysql://root:password@db/passenger
     - APP_SECRET_KEY=xi3aiGiewip1ze7MFei9haotvoo9Wo4k
     - SQLALCHEMY_TRACK_MODIFICATIONS=True
     - FILENAME_CSV=data.csv # Adding csv file

  db:
    restart: always
    image: mysql:5.7
    volumes:
      - /var/lib/mysql2:/var/lib/mysql
    environment:
       MYSQL_DATABASE: "passenger"
       MYSQL_ROOT_PASSWORD: password

  www:
    restart: always
    build: nginx/.
    links:
      - app
    depends_on:
      - app
    ports:
      - "80:80"
